version: '3.9'

services:
  postgres:
    image: postgis/postgis:13-3.1
    container_name: "postgres_container"
    volumes:
      - pgsed_data:/var/lib/postgresql/data
      - ./initialization.sql:/docker-entrypoint-initdb.d/initialization.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: aeroplane
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 1
    ports:
      - "5432:5432"
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "fastapi_container"
    volumes:
      - .:/appy
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1234@postgres_container:5432/aeroplane
    restart: always

volumes:
  pgsed_data:
